// src/config/errors.js
const ERRORS = Object.freeze({
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  MISSING_ROOM_ID: "MISSING_ROOM_ID",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  NOT_JOINED: "NOT_JOINED",
  INVALID_MESSAGE: "INVALID_MESSAGE",
  MESSAGE_TOO_LONG: "MESSAGE_TOO_LONG",
  PAYLOAD_INVALID: "PAYLOAD_INVALID",
  DM_PUBLISH_FAILED: "DM_PUBLISH_FAILED",
  CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
  MATERIAL_NOT_FOUND: "MATERIAL_NOT_FOUND",
  MATERIAL_CLASS_MISMATCH: "MATERIAL_CLASS_MISMATCH",
  CLASS_MISMATCH: "CLASS_MISMATCH",
});

module.exports = { ERRORS };
