// config/errors.js

const ERRORS = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PAYLOAD_INVALID: "PAYLOAD_INVALID",
  FORBIDDEN: "FORBIDDEN",

  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_JOINED: "NOT_JOINED",
  MISSING_ROOM_ID: "MISSING_ROOM_ID",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  CLASS_MISMATCH: "CLASS_MISMATCH",

  CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
  MATERIAL_NOT_FOUND: "MATERIAL_NOT_FOUND",
  MATERIAL_CLASS_MISMATCH: "MATERIAL_CLASS_MISMATCH",

  INVALID_MESSAGE: "INVALID_MESSAGE",
  MESSAGE_TOO_LONG: "MESSAGE_TOO_LONG",
  DM_PUBLISH_FAILED: "DM_PUBLISH_FAILED",
};

module.exports = { ERRORS };
