// config/errors.js

const ERRORS = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PAYLOAD_INVALID: "PAYLOAD_INVALID",
  FORBIDDEN: "FORBIDDEN",

  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_JOINED: "NOT_JOINED",
  MISSING_ROOM_ID: "MISSING_ROOM_ID",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_ENDED: "SESSION_ENDED",
  CLASS_MISMATCH: "CLASS_MISMATCH",

  CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
  MATERIAL_NOT_FOUND: "MATERIAL_NOT_FOUND",
  MATERIAL_CLASS_MISMATCH: "MATERIAL_CLASS_MISMATCH",

  INVALID_MESSAGE: "INVALID_MESSAGE",
  MESSAGE_TOO_LONG: "MESSAGE_TOO_LONG",
  DM_PUBLISH_FAILED: "DM_PUBLISH_FAILED",

  // ✅ #61
  PDF_FETCH_FAILED: "PDF_FETCH_FAILED",
  PDF_EXPORT_FAILED: "PDF_EXPORT_FAILED",
  // ✅ #93
  FILE_TYPE_INVALID: "FILE_TYPE_INVALID",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  MATERIAL_UPLOAD_FAILED: "MATERIAL_UPLOAD_FAILED",

  // ✅ #51
  POLL_ALREADY_ACTIVE:   "POLL_ALREADY_ACTIVE",
  POLL_NOT_FOUND:        "POLL_NOT_FOUND",
  POLL_INVALID_OPTION:   "POLL_INVALID_OPTION",
  POLL_ALREADY_ANSWERED: "POLL_ALREADY_ANSWERED",

  // ✅ #54
  QUESTION_EMPTY:       "QUESTION_EMPTY",
  QUESTION_TOO_LONG:    "QUESTION_TOO_LONG",
  QUESTION_SAVE_FAILED: "QUESTION_SAVE_FAILED",
  QUESTION_LIST_FAILED: "QUESTION_LIST_FAILED",

  // ✅ #56
  QUESTION_NOT_FOUND:        "QUESTION_NOT_FOUND",
  QUESTION_ALREADY_ANSWERED: "QUESTION_ALREADY_ANSWERED",
  QUESTION_ANSWER_FAILED:    "QUESTION_ANSWER_FAILED",

  // ✅ #60
  QUIZ_LIMIT_EXCEEDED: "QUIZ_LIMIT_EXCEEDED",
  QUIZ_NOT_FOUND:      "QUIZ_NOT_FOUND",
  QUIZ_ORDER_CONFLICT: "QUIZ_ORDER_CONFLICT",
  QUIZ_SAVE_FAILED:    "QUIZ_SAVE_FAILED",
};

module.exports = { ERRORS };
